### ISSUE TITLE
zebra_inverse.mzn problem is solved as UNSATISFIABLE by Gecode 6.3.0 and as satisfiable by other solvers

### ISSUE THREAD

**Issue by yurivict** [Gecode/gecode#106] opened 2021-05-07 10:15 UTC
zebra_inverse.mzn when ran through MiniZinc comes back as UNSATIDFIABLE with Gecode and as satisfiable with other solvers.

Result produced by Gecode must be wrong.

minizinc-2.5.5
Gecode rev. 9428cd8 which is a tail of the 6.3.0 branch
FreeBSD 12.2

**Comment by zayenz** [comment] 2021-05-07 11:56
If it is the Zebra Puzzle implementation by Håkan Kjellerstrand you mean (http://www.hakank.org/minizinc/zebra_inverse.mzn) then it is solved fine in the MiniZincIDE on Mac, which indicates that it is something problematic with your set-up.

Have you compiled Gecode yourself, and if so, have you tested that the compilation worked using the Gecode test suite?

Additionally, how are you compiling the MiniZinc model? The most recent MiniZinc IDE produces the attached FlatZinc file (.txt extension since GitHub won't attach fzn files) for the linked model when compiling for Gecode.
[hakank_zebra_inverse_for_gecode.txt](https://github.com/Gecode/gecode/files/6441345/hakank_zebra_inverse_for_gecode.txt)

**Comment by yurivict** [comment] 2021-05-07 19:14
Are there instructions on how to run tests?

Simple ```test``` target fails:
```
Could not find executable gecode-test
Looked in the following places:
gecode-test
gecode-test
Release/gecode-test
Release/gecode-test
Debug/gecode-test
Debug/gecode-test
MinSizeRel/gecode-test
MinSizeRel/gecode-test
RelWithDebInfo/gecode-test
RelWithDebInfo/gecode-test
Deployment/gecode-test
Deployment/gecode-test
Development/gecode-test
Development/gecode-test
Unable to find executable: gecode-test
```

There is no such executable.

Additionally, the ```test``` target seems to always rebuild the whole project.

**Comment by zayenz** [comment] 2021-05-07 19:52
A basic check can be done using `make check` which runs a subset of the tests.

The full test-suite can be executed first running `make test` which compiles the test executable and then running  the test using the compiled executable. The executable is available as `./test/test` and has various options for controlling the test run. For running it, the dynamic link path needs to be set to include the directory the newly built Gecode library files are located in. Note that there are some float tests that are currently failing (I'm currently looking into this), so passing the argument `-test -Float` is a good idea.

**Comment by yurivict** [comment] 2021-05-08 02:03
```check``` target prints this:
```
===>  Testing for gecode-6.3.0
ninja: error: unknown target 'check', did you mean 'help'?
*** Error code 1
```

```test``` target fails with the message above.

My system uses ninja cmake backend, so make is replaced with ninja.
There is also no ```test``` executable after the build anywhere in the directory.

**Comment by Dekker1** [comment] 2021-05-08 02:07
@yurivict CMake is not the default build system for Gecode. The check target is defined in the autotools Gecode build system.

```
mkdir build
cd build
../configure
make check
```

**Comment by yurivict** [comment] 2021-05-08 05:29
Autotools-built gecode-6.3.0 solves zebra_inverse.mzn fine.

Not sure how can this be that switch to cmake can cause this.

**Comment by zayenz** [comment] 2021-05-14 12:05
I'm not sure either what the differecn could be.

For clarity, have you checked if the generated FlatZinc files are equivalent with your two different builds?

**Comment by zayenz** [comment] 2021-06-04 08:32
With no way to reproduce and no further information, I will close this.

**Closed as completed by zayenz** 2021-06-04 08:32 UTC
